# Generated by Django 2.2.2 on 2019-06-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_num', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=2800)),
                ('message_id', models.CharField(max_length=20)),
                ('sent_to', models.CharField(max_length=15)),
                ('secret', models.CharField(max_length=20)),
                ('sent_timestamp', models.IntegerField()),
            ],
        ),
    ]
